test = {   'name': 'q2b',
    'points': 10,
    'suites': [   {   'cases': [   {'code': '>>> torch.isclose(network(torch.tensor([[0., 0.]])), torch.zeros(1), 0, 0.01).item()\nTrue', 'hidden': False, 'locked': False, 'points': 1},
                                   {'code': '>>> torch.isclose(network(torch.tensor([[1., 0.]])), torch.ones(1), 0, 0.01).item()\nTrue', 'hidden': False, 'locked': False, 'points': 1},
                                   {'code': '>>> torch.isclose(network(torch.tensor([[0., 1.]])), torch.ones(1), 0, 0.01).item()\nTrue', 'hidden': False, 'locked': False, 'points': 1},
                                   {'code': '>>> torch.isclose(network(torch.tensor([[1., 1.]])), torch.zeros(1), 0, 0.01).item()\nTrue', 'hidden': False, 'locked': False, 'points': 1}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
